### PR TITLE
Add support for "http" type; Add @microsoft/onedrive-file-picker

### PR DESCRIPTION
**Pull request by ujovlado**
Jira: https://keboola.atlassian.net/browse/UI-626

Related: https://github.com/keboola/kbc-ui/pull/4702

Changes:

- Add support for "http" type; Move to separate functions
- Add @microsoft/onedrive-file-picker
- Tune readme

---
Npm casti som sa nechytal, je to len prehodene do funkcie. Potom som tam pripravil dalsiu cast, ktore je schopna stiahnut subor cez `curl` a pouzit ho. Je to rychly workaround, nech to nemusime manualne nahravat do s3, atd. 

Kedze sa jedna o manualne stiahnutie (nie je potrebny ziadny config ani nic), tak som dal rovno celu zlozku do gitignore.

### CODE REVIEW

**Comment by ujovlado** [comment]
Screenshot_2020-04-20_16-44-02

**Comment by ujovlado** [comment]
Oka, diky, hodim sem  potom link.

**Comment by ujovlado** [comment]
Rovno som to chcel zmigrovat na travis-ci.com (preto ten posledny commit), ale je to nejake zblbnute.

**Comment by ujovlado** [comment]
https://assets-cdn.keboola.com/misc-ui/@microsoft/onedrive-file-picker/7.2.0/OneDrive.js

**Comment by natocTo** [comment]
Jo díky, už jsem to upravil v tom PR pro onedrive.

**Pull request merged**
